### ISSUE TITLE
压测的图片怎么生成的

### ISSUE THREAD

**Issue by JellyZero** [cloudwego/kitex-benchmark#55]
如题

**Comment by YangruiEmma** [comment]
代码在 https://github.com/cloudwego/kitex-benchmark/tree/main/scripts/reports

**Comment by JellyZero** [comment]
> 代码在 https://github.com/cloudwego/kitex-benchmark/tree/main/scripts/reports

命令是啥？具体怎么操作

**Comment by JellyZero** [comment]
@YangruiEmma 命令是啥？具体怎么操作

**Comment by joway** [comment]
没有命令，就是自己手写代码生成的，详细可以看下代码。

**Comment by li-jin-gou** [comment]
> @YangruiEmma 命令是啥？具体怎么操作

看下代码，使用 Python 中的 matplotlib 进行图片生成.......... @JellyZero
